using System.Text;

namespace Agent.Common.Llm;

/// <summary>
/// A person's report about one AI-generated answer: what kind of problem, an
/// optional note, and the answer itself — turned into a pre-filled e-mail or a
/// GitHub issue that the person reviews and sends. The app has no server, so
/// nothing leaves the machine until the person sends it themselves.
///
/// Required for the Microsoft Store: certification of submission 3 (2026-10-05)
/// failed policy 11.16 "Live Generative AI Content" — "products that contain
/// generative AI must provide a means for users to report inappropriate content
/// generated by the AI". Kept host-neutral so the WPF host can show the same
/// report from its own bot window.
/// </summary>
public sealed record AiContentReport(
    AiReportCategory Category,
    string Note,
    string Content,
    string? Model,
    string AppVersion,
    string Os)
{
    public const string SupportEmail = "psmon@live.co.kr";
    public const string IssuesUrl = "https://github.com/psmon/AgentZeroLite/issues/new";

    /// <summary>How much of the answer is quoted. A mailto: or issue URL that grows past a few KB is cut by browsers and mail clients.</summary>
    public const int MaxQuotedChars = 1500;

    public static readonly IReadOnlyList<AiReportCategory> Categories =
        [AiReportCategory.Inappropriate, AiReportCategory.Harmful, AiReportCategory.Inaccurate, AiReportCategory.Other];

    public static string Describe(AiReportCategory category) => category switch
    {
        AiReportCategory.Inappropriate => "Inappropriate or offensive",
        AiReportCategory.Harmful => "Harmful or dangerous",
        AiReportCategory.Inaccurate => "Wrong or misleading",
        _ => "Other",
    };

    public string Subject => $"[AI content report] {Describe(Category)}";

    public string Body()
    {
        var quoted = Content.Length <= MaxQuotedChars ? Content : Content[..MaxQuotedChars] + "\n… (cut)";
        var sb = new StringBuilder();
        sb.AppendLine($"Category: {Describe(Category)}");
        sb.AppendLine($"Model: {(string.IsNullOrWhiteSpace(Model) ? "(not set)" : Model)}");
        sb.AppendLine($"App: AgentZero Lite {AppVersion} · {Os}");
        sb.AppendLine();
        sb.AppendLine("What is wrong:");
        sb.AppendLine(string.IsNullOrWhiteSpace(Note) ? "(no note)" : Note.Trim());
        sb.AppendLine();
        sb.AppendLine("The AI answer:");
        sb.AppendLine("----");
        sb.AppendLine(quoted);
        sb.AppendLine("----");
        return sb.ToString();
    }

    /// <summary>A mailto: link to the support contact with subject and body filled in.</summary>
    public string MailtoUri() =>
        $"mailto:{SupportEmail}?subject={Uri.EscapeDataString(Subject)}&body={Uri.EscapeDataString(Body())}";

    /// <summary>The repository's new-issue page with title and body filled in.</summary>
    public string IssueUri() =>
        $"{IssuesUrl}?title={Uri.EscapeDataString(Subject)}&body={Uri.EscapeDataString(Body())}&labels=ai-content-report";
}

public enum AiReportCategory { Inappropriate, Harmful, Inaccurate, Other }
