// <auto-generated />
using System;
using Agent.Common.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Agent.Common.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260503105352_AddTokenAccountAliasAndCheckpointAccount")]
    partial class AddTokenAccountAliasAndCheckpointAccount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0-preview.3.25171.6");

            modelBuilder.Entity("Agent.Common.Data.Entities.AppWindowState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsBotDocked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMaximized")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastActiveGroupIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastActiveTabIndex")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Left")
                        .HasColumnType("REAL");

                    b.Property<string>("OnboardingDismissedVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Top")
                        .HasColumnType("REAL");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("AppWindowStates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Height = 720.0,
                            IsBotDocked = true,
                            IsMaximized = false,
                            LastActiveGroupIndex = 0,
                            LastActiveTabIndex = 0,
                            Left = 0.0,
                            OnboardingDismissedVersion = "",
                            Top = 0.0,
                            Width = 860.0
                        });
                });

            modelBuilder.Entity("Agent.Common.Data.Entities.CliDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Arguments")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CliDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExePath = "cmd.exe",
                            IsBuiltIn = true,
                            Name = "CMD",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 2,
                            ExePath = "powershell.exe",
                            IsBuiltIn = true,
                            Name = "PW5",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 3,
                            ExePath = "pwsh.exe",
                            IsBuiltIn = true,
                            Name = "PW7",
                            SortOrder = 2
                        });
                });

            modelBuilder.Entity("Agent.Common.Data.Entities.CliGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DirectoryPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CliGroups");
                });

            modelBuilder.Entity("Agent.Common.Data.Entities.CliTab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CliDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CliDefinitionId");

                    b.HasIndex("GroupId");

                    b.ToTable("CliTabs");
                });

            modelBuilder.Entity("Agent.Common.Data.Entities.ClipboardEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CopiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ClipboardEntries");
                });

            modelBuilder.Entity("Agent.Common.Data.Entities.TokenAccountAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Vendor", "AccountKey")
                        .IsUnique();

                    b.ToTable("TokenAccountAliases");
                });

            modelBuilder.Entity("Agent.Common.Data.Entities.TokenSourceCheckpoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ByteOffset")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LineCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceFile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceFile")
                        .IsUnique();

                    b.ToTable("TokenSourceCheckpoints");
                });

            modelBuilder.Entity("Agent.Common.Data.Entities.TokenUsageRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CacheCreateTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CacheReadTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cwd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GitBranch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawRequestId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ReasoningTokens")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SourceLine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceFile", "SourceLine");

                    b.HasIndex("Vendor", "RawRequestId");

                    b.HasIndex("Vendor", "RecordedAt");

                    b.ToTable("TokenUsageRecords");
                });

            modelBuilder.Entity("Agent.Common.Data.Entities.CliTab", b =>
                {
                    b.HasOne("Agent.Common.Data.Entities.CliDefinition", "CliDefinition")
                        .WithMany()
                        .HasForeignKey("CliDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Agent.Common.Data.Entities.CliGroup", "Group")
                        .WithMany("Tabs")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CliDefinition");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Agent.Common.Data.Entities.CliGroup", b =>
                {
                    b.Navigation("Tabs");
                });
#pragma warning restore 612, 618
        }
    }
}
